# Generated by Django 6.1.1 on 2026-09-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlog',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_logs', to='support.conversation'),
        ),
        migrations.AlterField(
            model_name='agentlog',
            name='event_type',
            field=models.CharField(choices=[('support', 'Support Assistant'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result'), ('manager', 'Manager Assistant'), ('risk', 'Risk Assistant'), ('final', 'Final Reply')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20),
        ),
    ]
