# Generated by Django 6.1.1 on 2026-09-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prices',
            new_name='price',
        ),
    ]
