# Generated by Django 6.1.1 on 2026-09-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
